#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.3.3 effective-5.10 (swiftlang-6.3.3.1.3 clang-2100.1.1.101)
#ifndef ADCASHFRAMEWORK_SWIFT_H
#define ADCASHFRAMEWORK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif // defined(__OBJC__)
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
#  if __has_feature(generalized_swift_name)
#   define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
#  else
#   define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
#  endif
# else
#  define SWIFT_ENUM(_type, _name, _extensibility) _type _name; enum 
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM_TAG)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM_TAG enum
# else
#  define SWIFT_ENUM_TAG
# endif
#endif
#if !defined(SWIFT_ENUM_FWD_DECL)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM_FWD_DECL(_type, _name) enum _name : _type;
# else
#  define SWIFT_ENUM_FWD_DECL(_type, _name) typedef _type _name;
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_AVAILABILITY_DOMAIN)
# define SWIFT_AVAILABILITY_DOMAIN(dom, ...) __attribute__((availability(domain: dom, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if !__has_feature(nullability)
# define _Nonnull
# define _Nullable
# define _Null_unspecified
#elif !defined(__OBJC__)
# pragma clang diagnostic ignored "-Wnullability-extension"
#endif
#if !__has_feature(nullability_nullable_result)
# define _Nullable_result _Nullable
#endif
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="AdCashFramework",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__cplusplus)
extern "C" {
#endif

#if defined(__cplusplus)
} // extern "C"
#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import APSSPSDK;
@import CoreFoundation;
@import ObjectiveC;
@import UIKit;
#endif

#endif // defined(__OBJC__)
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="AdCashFramework",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

@class NSString;
SWIFT_CLASS("_TtC15AdCashFramework16AdCashErrorModel")
@interface AdCashErrorModel : NSObject
@property (nonatomic, readonly) NSInteger code;
@property (nonatomic, readonly, copy) NSString * _Nonnull type;
@property (nonatomic, readonly, copy) NSString * _Nonnull message;
@property (nonatomic, readonly, copy) NSString * _Nonnull desc;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_ENUM_FWD_DECL(NSInteger, LogLevel)
SWIFT_CLASS("_TtC15AdCashFramework10AdCashInit")
@interface AdCashInit : NSObject
+ (void)settingWithAppId:(NSString * _Nonnull)appId appSecretKey:(NSString * _Nonnull)appSecretKey logLevel:(enum LogLevel)logLevel;
+ (void)avatyeSettingWithLogLevel:(enum LogLevel)logLevel;
+ (void)devModeChangeWithValue:(NSString * _Nullable)value;
+ (void)trackSetting;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC15AdCashFramework15AdCashMediation")
@interface AdCashMediation : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (void)initializeAppLovin:(NSString * _Nonnull)sdkKey;
- (void)initializeCaulyWithAppId:(NSString * _Nonnull)appId appCode:(NSString * _Nonnull)appCode;
- (void)initializeMintegralWithAppID:(NSString * _Nonnull)appID apiKey:(NSString * _Nonnull)apiKey;
- (void)initializeVungle:(NSString * _Nonnull)vungleKey;
- (void)initializeGAM;
- (void)initializePangle:(NSString * _Nonnull)pangleKey;
@end

@class UIView;
SWIFT_CLASS("_TtC15AdCashFramework14AdCashNativeAd")
@interface AdCashNativeAd : NSObject
/// NAM(네이버) 렌더러를 등록한다. <code>requestAd()</code> 전에 호출해야 한다.
/// \param namNativeAdRenderer <code>APSSPNAMNativeAdRenderer</code>. 타입이 NAM adapter pod 소속이라 <code>Any!</code> 로 받는다.
///
/// \param superView 현재 사용하지 않는다(<code>NativeAdView.applyNAMRenderer</code> 참고). 호환을 위해 유지.
///
- (void)setNAMRenderer:(id _Null_unspecified)namNativeAdRenderer superView:(UIView * _Nonnull)superView;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@protocol BannerAdLoaderDelegate;
@class UIViewController;
SWIFT_ENUM_FWD_DECL(NSInteger, BannerAdSize)
@class UINib;
SWIFT_ENUM_FWD_DECL(NSInteger, NAMType)
SWIFT_CLASS_NAMED("BannerAdLoader")
@interface AVABannerAdLoader : NSObject
@property (nonatomic, weak) id <BannerAdLoaderDelegate> _Nullable delegate;
- (nonnull instancetype)initWithRootVC:(UIViewController * _Nonnull)rootVC placementId:(NSString * _Nonnull)placementId size:(enum BannerAdSize)size OBJC_DESIGNATED_INITIALIZER;
/// warning:
/// <code>adView</code> 인자는 <em>4.0.0 이후 아무 동작도 하지 않는다.</em>
/// 2.x 의 레거시 <code>AdPopcornSSPBannerView(..., view:rootViewController:)</code> 는 배너를 그려 넣을 호스트 뷰를
/// 인자로 받았고 이 값이 거기에 전달됐다. APSSPSDK 의 <code>APSSPBannerView(appKey:placementId:bannerSize:)</code> 에는
/// 그 인자가 없어(rootViewController 는 프로퍼티로 분리) 전달 경로가 사라졌다.
/// 로드 성공 시 델리게이트로 넘어가는 뷰는 이 인자와 무관하게 항상 SSP/House/Native 가 만든 실제 광고 뷰다.
/// 인자를 실제 컨테이너로 되살리면 <code>onBannerLoaded</code> 가 넘기는 뷰의 정체가 바뀌는 동작 변경이 되므로,
/// 되살리지 않고 표시만 남긴다. 시그니처는 이 인자를 넘기는 배포된 소비앱의 컴파일 호환을 위해 유지한다.
- (nonnull instancetype)initWithRootVC:(UIViewController * _Nonnull)rootVC placementId:(NSString * _Nonnull)placementId size:(enum BannerAdSize)size adView:(UIView * _Nullable)adView SWIFT_DEPRECATED_MSG("adView 인자는 동작하지 않습니다. init(rootVC:placementId:size:) 를 사용하고, 광고 뷰는 onBannerLoaded(_:adView:size:) 로 받으세요.");
- (nonnull instancetype)setConfigWithAppId:(NSString * _Nonnull)appId appSecretKey:(NSString * _Nonnull)appSecretKey;
- (void)requestAd;
- (void)removeAd;
- (void)setNAMNativeWith:(void (^ _Nonnull)(AdCashNativeAd * _Nonnull, UINib * _Nonnull))configuration;
- (void)setNAMNativeWithType:(enum NAMType)type width:(CGFloat)width with:(void (^ _Nonnull)(AdCashNativeAd * _Nonnull, UIView * _Nonnull))configuration;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_PROTOCOL("_TtP15AdCashFramework22BannerAdLoaderDelegate_")
@protocol BannerAdLoaderDelegate <NSObject>
- (void)onBannerLoaded:(NSString * _Nonnull)apid adView:(UIView * _Nonnull)adView size:(CGSize)size;
- (void)onBannerFailed:(NSString * _Nonnull)apid error:(AdCashErrorModel * _Nonnull)error;
- (void)onBannerClicked:(NSString * _Nonnull)apid;
- (void)onBannerRemoved:(NSString * _Nonnull)apid;
@end

typedef SWIFT_ENUM(NSInteger, BannerAdSize, open) {
  BannerAdSizeW320XH50 = 0,
  BannerAdSizeW320XH100 = 1,
  BannerAdSizeW300XH250 = 2,
  BannerAdSizeDYNAMIC = 3,
};

@protocol BannerAdWidgetDelegate;
@class NSCoder;
SWIFT_CLASS_NAMED("BannerAdView")
@interface AVABannerAdView : UIView
@property (nonatomic, weak) id <BannerAdWidgetDelegate> _Nullable delegate;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder SWIFT_UNAVAILABLE;
- (nonnull instancetype)setConfigWithAppId:(NSString * _Nonnull)appId appSecretKey:(NSString * _Nonnull)appSecretKey;
- (void)setBannerAdWithRootVC:(UIViewController * _Nonnull)rootVC placementId:(NSString * _Nonnull)placementId size:(enum BannerAdSize)size;
- (void)setNAMNativeWith:(void (^ _Nonnull)(AdCashNativeAd * _Nonnull, UINib * _Nonnull))configuration;
- (void)setNAMNativeWithType:(enum NAMType)type width:(CGFloat)width with:(void (^ _Nonnull)(AdCashNativeAd * _Nonnull, UIView * _Nonnull))configuration;
- (void)requestAd;
- (void)removeAd;
- (void)releaseAd;
@end

@interface AVABannerAdView (SWIFT_EXTENSION(AdCashFramework)) <BannerAdLoaderDelegate>
- (void)onBannerLoaded:(NSString * _Nonnull)apid adView:(UIView * _Nonnull)adView size:(CGSize)size;
- (void)onBannerFailed:(NSString * _Nonnull)apid error:(AdCashErrorModel * _Nonnull)error;
- (void)onBannerClicked:(NSString * _Nonnull)apid;
- (void)onBannerRemoved:(NSString * _Nonnull)apid;
@end

SWIFT_PROTOCOL("_TtP15AdCashFramework22BannerAdWidgetDelegate_")
@protocol BannerAdWidgetDelegate
- (void)onBannerLoaded:(NSString * _Nonnull)apid;
- (void)onBannerFailed:(NSString * _Nonnull)apid error:(AdCashErrorModel * _Nonnull)error;
- (void)onBannerClicked:(NSString * _Nonnull)apid;
- (void)onBannerRemoved:(NSString * _Nonnull)apid;
@end

SWIFT_PROTOCOL("_TtP15AdCashFramework22InterstitialAdDelegate_")
@protocol InterstitialAdDelegate <NSObject>
- (void)onInterstitialLoaded:(NSString * _Nonnull)apid;
- (void)onInterstitialOpened:(NSString * _Nonnull)apid;
- (void)onInterstitialClosed:(NSString * _Nonnull)apid isCompleted:(BOOL)isCompleted;
- (void)onInterstitialFailed:(NSString * _Nonnull)apid error:(AdCashErrorModel * _Nonnull)error;
- (void)onInterstitialClicked:(NSString * _Nonnull)apid;
@end

SWIFT_ENUM_FWD_DECL(NSInteger, InterstitialAdType)
SWIFT_CLASS_NAMED("InterstitialAdLoader")
@interface AVAInterstitialAdLoader : NSObject
@property (nonatomic, weak) id <InterstitialAdDelegate> _Nullable delegate;
@property (nonatomic, readonly) enum InterstitialAdType loadedAdType;
- (nonnull instancetype)initWithPlacementId:(NSString * _Nonnull)placementId rootViewController:(UIViewController * _Nonnull)rootViewController OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)setConfigWithAppId:(NSString * _Nonnull)appId appSecretKey:(NSString * _Nonnull)appSecretKey;
- (void)showAd;
- (void)requestAd;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class APSSPInterstitialAd;
SWIFT_ENUM_FWD_DECL(NSInteger, APSSPNetworkError)
@interface AVAInterstitialAdLoader (SWIFT_EXTENSION(AdCashFramework)) <APSSPInterstitialAdDelegate>
- (void)apsspInterstitialAdClosedWithInterstitialAd:(APSSPInterstitialAd * _Nonnull)interstitialAd;
- (void)apsspInterstitialAdClickedWithInterstitialAd:(APSSPInterstitialAd * _Nonnull)interstitialAd;
- (void)apsspInterstitialAdLoadSuccessWithInterstitialAd:(APSSPInterstitialAd * _Nonnull)interstitialAd;
- (void)apsspInterstitialAdShowSuccessWithInterstitialAd:(APSSPInterstitialAd * _Nonnull)interstitialAd;
- (void)apsspInterstitialAdLoadFailWithInterstitialAd:(APSSPInterstitialAd * _Nonnull)interstitialAd error:(enum APSSPNetworkError)error;
- (void)apsspInterstitialAdShowFailWithInterstitialAd:(APSSPInterstitialAd * _Nonnull)interstitialAd error:(enum APSSPNetworkError)error;
@end

@class APSSPInterstitialVideoAd;
@interface AVAInterstitialAdLoader (SWIFT_EXTENSION(AdCashFramework)) <APSSPInterstitialVideoAdDelegate>
- (void)apsspInterstitialVideoAdClosedWithInterstitialVideoAd:(APSSPInterstitialVideoAd * _Nonnull)interstitialVideoAd;
- (void)apsspInterstitialVideoAdShowFailWithInterstitialVideoAd:(APSSPInterstitialVideoAd * _Nonnull)interstitialVideoAd error:(enum APSSPNetworkError)error;
- (void)apsspInterstitialVideoAdLoadSuccessWithInterstitialVideoAd:(APSSPInterstitialVideoAd * _Nonnull)interstitialVideoAd;
- (void)apsspInterstitialVideoAdShowSuccessWithInterstitialVideoAd:(APSSPInterstitialVideoAd * _Nonnull)interstitialVideoAd;
- (void)apsspInterstitialVideoAdClickedWithInterstitialVideoAd:(APSSPInterstitialVideoAd * _Nonnull)interstitialVideoAd;
- (void)apsspInterstitialVideoAdLoadFailWithInterstitialVideoAd:(APSSPInterstitialVideoAd * _Nonnull)interstitialVideoAd error:(enum APSSPNetworkError)error;
@end

@class APSSPRewardVideoAd;
@interface AVAInterstitialAdLoader (SWIFT_EXTENSION(AdCashFramework)) <APSSPRewardVideoAdDelegate>
- (void)apsspRewardVideoAdClosedWithRewardVideoAd:(APSSPRewardVideoAd * _Nonnull)rewardVideoAd;
- (void)apsspRewardVideoAdShowFailWithRewardVideoAd:(APSSPRewardVideoAd * _Nonnull)rewardVideoAd error:(enum APSSPNetworkError)error;
- (void)apsspRewardVideoAdLoadSuccessWithRewardVideoAd:(APSSPRewardVideoAd * _Nonnull)rewardVideoAd;
- (void)apsspRewardVideoAdShowSuccessWithRewardVideoAd:(APSSPRewardVideoAd * _Nonnull)rewardVideoAd;
- (void)apsspRewardVideoAdClickedWithRewardVideoAd:(APSSPRewardVideoAd * _Nonnull)rewardVideoAd;
- (void)apsspRewardVideoAdLoadFailWithRewardVideoAd:(APSSPRewardVideoAd * _Nonnull)rewardVideoAd error:(enum APSSPNetworkError)error;
- (void)apsspRewardVideoAdPlayCompletedWithRewardVideoAd:(APSSPRewardVideoAd * _Nonnull)rewardVideoAd adNetworkNo:(NSInteger)adNetworkNo completed:(BOOL)completed;
@end

typedef SWIFT_ENUM(NSInteger, InterstitialAdType, open) {
  InterstitialAdTypeInterstitial = 0,
  InterstitialAdTypeInterstitialNative = 1,
  InterstitialAdTypeInterstitialBox = 2,
  InterstitialAdTypeInterstitialHouse = 3,
  InterstitialAdTypeInterstitialVideo = 4,
  InterstitialAdTypeInterstitialRewardVideo = 5,
};

typedef SWIFT_ENUM(NSInteger, LogLevel, open) {
  LogLevelDebug = 1,
  LogLevelInfo = 2,
  LogLevelError = 3,
  LogLevelNone = 4,
};

typedef SWIFT_ENUM(NSInteger, NAMType, open) {
  NAMTypeImage = 0,
  NAMTypeSmart = 1,
};

SWIFT_CLASS("_TtC15AdCashFramework15UnifiedAdLoader")
@interface UnifiedAdLoader : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

#endif // defined(__OBJC__)
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
